name: workspace_malconv_keras
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - pip=22
  - keras=2.2.4
  - tensorflow-mkl=1.15
  - numpy=1.18.5
  - scikit-learn=0.21.3
  - pip:
    - pandas==1.0.5  