name: workspace_ember_cpu
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - pandas>=0.24.2
  - numpy>=1.16.3
  - scikit-learn>=0.20.3
  - py-lief=0.9.0
  - tqdm>=4.31.0
  - lightgbm>=2.2.3